# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-08-01 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('skills', multiselectfield.db.fields.MultiSelectField(choices=[('Py', 'Python'), ('Dj', 'Django'), ('Fl', 'Flask'), ('RAPP', 'Rest API')], max_length=200)),
                ('locations', multiselectfield.db.fields.MultiSelectField(choices=[('Hyd', 'Hyderabad'), ('Bang', 'Banglore'), ('Che', 'Chennai'), ('Mum', 'Mumbai')], max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('date', models.DateField(max_length=100)),
            ],
        ),
    ]
